# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'advertising-service'
#     static_configs:
#       - targets: ['host.docker.internal:5000']

#   - job_name: 'golang-api'
#     static_configs:
#       - targets: ['golang-api:8080']
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'golang_api'
    static_configs:
      - targets: ['localhost:9091']
